const DATA_URL="../data/financial_data.csv";let rows=[],charts={};
const names={revenue:"매출액",operating_margin:"영업이익률",net_margin:"순이익률",roe:"ROE",roa:"ROA",debt_to_equity:"부채비율",equity_ratio:"자기자본비율",current_ratio:"유동비율",cfo:"영업현금흐름",fcf:"FCF"};
function csv(t){const a=t.trim().split(/\r?\n/),h=a.shift().split(",");return a.map(x=>{const v=x.split(",");const o={};h.forEach((k,i)=>o[k]=v[i]===""?null:Number(v[i]));return o})}
function enrich(d){return d.map((r,i)=>{const p=d[i-1],aa=p?(r.total_assets+p.total_assets)/2:null,ae=p?(r.total_equity+p.total_equity)/2:null;return Object.assign({},r,{revenue_growth:p?r.revenue/p.revenue-1:null,operating_margin:r.operating_income/r.revenue,net_margin:r.net_income/r.revenue,roa:aa?r.net_income/aa:null,roe:ae?r.net_income/ae:null,debt_to_equity:r.total_liabilities/r.total_equity,equity_ratio:r.total_equity/r.total_assets,current_ratio:r.current_assets/r.current_liabilities,cfo:r.operating_cash_flow,fcf:r.operating_cash_flow!=null&&r.capex!=null?r.operating_cash_flow-r.capex:null})})}
function money(v){return v==null?"-":"₩"+(v/1e6).toFixed(1)+"조"}function pct(v){return v==null?"-":(v*100).toFixed(1)+"%"}
function chart(id,labels,sets){if(charts[id])charts[id].destroy();charts[id]=new Chart(document.getElementById(id),{type:"line",data:{labels:labels,datasets:sets},options:{responsive:true,tension:.25,spanGaps:true,plugins:{legend:{position:"top"}}}})}
function line(label,data){return{label:label,data:data,borderWidth:2,tension:.25,spanGaps:true}}
function render(){const start=Number(document.getElementById("startYear").value),v=rows.filter(r=>r.year>=start).slice(-10),lab=v.map(r=>r.year),m=document.getElementById("metric").value,latest=v[v.length-1];
document.getElementById("chartTitle").textContent=names[m]+" 10년 추이";chart("trendChart",lab,[line(names[m],v.map(r=>r[m]))]);
chart("profitChart",lab,[line("영업이익률",v.map(r=>r.operating_margin*100)),line("순이익률",v.map(r=>r.net_margin*100))]);
chart("stabilityChart",lab,[line("부채비율",v.map(r=>r.debt_to_equity*100)),line("자기자본비율",v.map(r=>r.equity_ratio*100)),line("유동비율",v.map(r=>r.current_ratio*100))]);
chart("cashChart",lab,[line("영업현금흐름",v.map(r=>r.cfo)),line("FCF",v.map(r=>r.fcf))]);
chart("growthChart",lab,[line("매출 성장률",v.map(r=>r.revenue_growth*100)),line("ROE",v.map(r=>r.roe*100))]);
document.getElementById("kpis").innerHTML=[["매출액",money(latest.revenue)],["영업이익률",pct(latest.operating_margin)],["ROE",pct(latest.roe)],["FCF",money(latest.fcf)]].map(x=>'<div class="kpi"><div class="label">'+x[0]+'</div><div class="value">'+x[1]+'</div><div class="year">'+latest.year+'년</div></div>').join("");
const cols=["year","revenue","operating_income","net_income","operating_margin","net_margin","roa","roe","debt_to_equity","equity_ratio","current_ratio","cfo","fcf"];let h="<thead><tr>"+cols.map(c=>"<th>"+c+"</th>").join("")+"</tr></thead><tbody>";v.forEach(r=>{h+="<tr>";cols.forEach(c=>{let z=r[c];if(c==="year")h+="<td>"+z+"</td>";else if(z==null)h+="<td>-</td>";else if(["operating_margin","net_margin","roa","roe","debt_to_equity","equity_ratio","current_ratio"].includes(c))h+="<td>"+pct(z)+"</td>";else h+="<td>"+money(z)+"</td>"});h+="</tr>"});document.getElementById("dataTable").innerHTML=h+"</tbody>"}
fetch(DATA_URL).then(r=>r.text()).then(t=>{rows=enrich(csv(t));const years=rows.filter(r=>r.year>=2016).map(r=>r.year);document.getElementById("startYear").innerHTML=years.map(y=>'<option value="'+y+'">'+y+'</option>').join("");document.getElementById("startYear").value=Math.max(2016,years[years.length-10]||2016);render()});document.getElementById("startYear").addEventListener("change",render);document.getElementById("metric").addEventListener("change",render);
